#!/bin/sh
set -e
for x in noroots-parmnt-parm nw-parm-{pre,post}idx; do
  notangle -L -R${x}.cpp parm.nw >${x}.cpp
  g++ --std=c++98 -O2 -Wall -Wextra -o $x{,.cpp}
  g++ -O2 -Wall -Wextra -o $x{,.cpp}
done
noweave -delay -index parm.nw >parm.tex; pdflatex parm; pdflatex parm; pdflatex parm
noweave -delay -filter l2h -index -html parm.nw | htmltoc > parm.html
